name: Makefile CI

on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Release tag'     
        required: true
        default: '0.0.0'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run Make
      run: make
    - name: Zip Extension
      run: |
        cd /home/runner/build
        zip ubuntuptime.zip extension.js metadata.json
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "/home/runner/build/ubuntuptime.zip"
        name: Latest release ( ${{ github.event.inputs.release }} )
        tag: ${{ github.event.inputs.release }}
        prerelease: false
        skipIfReleaseExists: false
        makeLatest: true
        allowUpdates: true
        artifactErrorsFailBuild: true
