name: Makefile CI

on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Release tag'     
        required: true
        default: '0.0.0'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run Make
      run: make
    - uses: montudor/action-zip@v1
      with:
        args: zip -qq -r ubuntuptime.zip "$(HOME)/.local/share/gnome-shell/extensions/kosmicteal+ubuntuptime@kosmicteal.local"
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "ubuntuptime.zip"
        name: Latest release ( ${{ github.event.inputs.release }} )
        tag: ${{ github.event.inputs.release }}
        prerelease: false
        skipIfReleaseExists: false
        makeLatest: true
        allowUpdates: true
        artifactErrorsFailBuild: true
